# Generated by Django 5.2.8 on 2026-04-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_user_reminder_time_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encourage_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
