# Generated by Django 5.2.8 on 2026-03-15 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='対象年')),
                ('month', models.IntegerField(verbose_name='対象月')),
                ('post_type', models.CharField(choices=[('income', '収入'), ('expense', '支出')], max_length=10, verbose_name='収支区分')),
                ('household_size', models.IntegerField(verbose_name='世帯人数')),
                ('memo', models.TextField(blank=True, max_length=500, verbose_name='メモ')),
                ('total_amount', models.IntegerField(default=0, verbose_name='合計金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
