# Generated by Django 5.2.8 on 2026-03-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_data',
            field=models.JSONField(default=dict, verbose_name='カテゴリ別内訳'),
        ),
    ]
