# Generated by Django 5.2.8 on 2026-04-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_colors',
            field=models.JSONField(default=dict, verbose_name='カテゴリー色情報'),
        ),
    ]
