# Generated by Django 5.2.8 on 2026-04-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='household_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='家計簿名'),
        ),
    ]
