# Generated by Django 5.2.8 on 2026-04-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0008_householdaccount_alter_transaction_user_and_more'),
        ('posts', '0004_post_household_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='households.householdaccount', verbose_name='家計簿'),
        ),
    ]
