# Generated by Django 5.2.8 on 2026-05-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_data',
            field=models.JSONField(default=dict, verbose_name='カテゴリー別内訳'),
        ),
    ]
