# Generated by Django 5.2.8 on 2026-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#9c6d5c', max_length=7),
        ),
    ]
