# Generated by Django 5.2.8 on 2026-04-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_category_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
