# Generated by Django 5.2.8 on 2026-04-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0005_alter_category_options_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('income', '収入'), ('expense', '支出')], default='expense', max_length=10)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'unique_together': {('category_type', 'color')},
            },
        ),
    ]
