# Generated by Django 5.2.8 on 2026-04-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_customcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
