"""
Django settings for first_project project.
Generated by 'django-admin startproject' using Django 5.2.7.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path  # ファイルパスを扱うモジュールのインポート
import os  # OSのパス操作モジュールのインポート
from dotenv import load_dotenv  # .envファイルから環境変数を読み込むモジュールのインポート

# .envファイルの内容を環境変数として読み込む
load_dotenv()


# プロジェクトのルートディレクトリ
BASE_DIR = Path(__file__).resolve().parent.parent
# テンプレートディレクトリのパス
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

# 開発環境用の設定（本番環境では変更が必要）
SECRET_KEY = 'django-insecure-m(!u0(y*zv!5=l(y&zg@^t^)9)%4*z(l-8oowk6obj%iupwzt3'

# デバッグモード（本番環境ではFalseに変更する）
DEBUG = True

# アクセスを許可するホスト名の一覧
ALLOWED_HOSTS = []

# インストール済みアプリの一覧
INSTALLED_APPS = [
    'django.contrib.admin',       # 管理画面
    'django.contrib.auth',        # 認証機能
    'django.contrib.contenttypes', # コンテンツタイプ管理
    'django.contrib.sessions',    # セッション管理
    'django.contrib.messages',    # メッセージ表示
    'django.contrib.staticfiles', # 静的ファイル管理
    'portfolio',  # ポートフォリオアプリ
    'home',       # ホームアプリ
    'accounts',   # アカウント管理アプリ
    'households', # 家計簿アプリ
    'posts',      # 投稿アプリ
]

# リクエスト処理の中間処理（セキュリティ・認証・CSRFなど）
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URLルーティングの起点となるファイルの指定
ROOT_URLCONF = 'first_project.urls'

# テンプレートエンジンの設定
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # テンプレートの検索ディレクトリ
        'DIRS': [BASE_DIR / "templates"],
        # 各アプリのtemplatesフォルダを自動検索する設定
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 現在選択中の家計簿をテンプレート全体に渡すカスタムプロセッサー
                'home.context_processors.current_household',
            ],
        },
    },
]

# WSGIアプリケーションの指定
WSGI_APPLICATION = 'first_project.wsgi.application'

# データベースの設定（開発環境ではSQLiteを使用）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# カスタムユーザーモデルの指定
AUTH_USER_MODEL = 'accounts.User'

# パスワード強度チェックのバリデーター設定
AUTH_PASSWORD_VALIDATORS = [
    {
        # ユーザー情報との類似性チェック
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 最低文字数チェック
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # よく使われるパスワードのチェック
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # 数字のみのパスワードの禁止
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 表示言語の設定（日本語）
LANGUAGE_CODE = 'ja'
# タイムゾーンの設定（日本時間）
TIME_ZONE = 'Asia/Tokyo'
# 国際化機能の有効化
USE_I18N = True
# タイムゾーン対応の有効化
USE_TZ = True

# 静的ファイル（CSS・JavaScript・画像など）のURL
STATIC_URL = 'static/'

# モデルの主キーに使用する自動採番フィールドの型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ログインのURLとログイン成功後のリダイレクト先
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "home:home"

# パスワードリセットリンクの有効期限（30分 = 1800秒）
PASSWORD_RESET_TIMEOUT = 1800

# メディアファイル（アップロードされた画像など）の設定
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# メール設定（Gmail経由でメールを送信する）
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # SMTPでメール送信
EMAIL_HOST = 'smtp.gmail.com'  # GmailのSMTPサーバー
EMAIL_PORT = 587  # TLS用のポート番号
EMAIL_USE_TLS = True  # TLS暗号化を有効にする
EMAIL_HOST_USER = 'kakeimamorukun@gmail.com'  # 送信元のGmailアドレス
EMAIL_HOST_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD')  # .envから取得したGmailアプリパスワード
DEFAULT_FROM_EMAIL = 'kakeimamorukun@gmail.com'  # 送信元メールアドレス